const routeConfig = {
	'brands': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'cart_items': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'carts': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'categories': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'public',
		update: 'admin',
		delete: 'admin',
	},
	'customers': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'import_invoice_details': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'import_invoices': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'inventory': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'order_details': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'orders': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'payment_methods': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'product_images': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'product_promotions': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'product_sizes': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'products': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'promotions': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'reviews': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'shipping_methods': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'sizes': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'suppliers': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'transactions': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'users': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'warehouses': {
		getAll: 'public',
		getAllWithoutPagination: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
};
export default routeConfig;
